files:
  include:
    - "src/**/*.s+(a|c)ss"
  ignore:
    - "node_modules/**/*.s+(a|c)ss"
rules:
  variable-name-format:
    - 2
    - convention: camelcase
  function-name-format:
    - 2
    - convention: camelcase
  placeholder-name-format:
    - 2
    - convention: camelcase
  border-zero:
    - 2
    - conversion: '0'
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  leading-zero:
    - 2
  hex-notation:
    - 2
    - style: uppercase
  hex-length:
    - 2
    - style: long
  property-sort-order:
    - 2
    - order: concentric
  force-element-nesting:
    - 2
  final-newline:
    - 2
  single-line-per-selector:
    - 2
  declarations-before-nesting:
    - 2
  space-before-brace:
    - 2
  empty-line-between-blocks:
    - 2
  no-color-keywords:
    - 2
  no-color-literals:
    - 2
  space-after-colon:
    - 2
  indentation:
    - 2
  quotes:
    - 2
  one-declaration-per-line:
    - 2
  nesting-depth:
    - 2
    - max-depth: 4
  clean-import-paths:
    - 2
    - filename-extension: false
  no-ids:
    - 0
  no-vendor-prefixes:
    - 0
  force-pseudo-nesting:
    - 0
  no-css-comments:
    - 0
  placeholder-in-extend:
    - 0
